# Generated by Django 5.2.4 on 2025-07-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='initials',
            field=models.CharField(default='DEF', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Sid', max_length=50),
            preserve_default=False,
        ),
    ]
