# fly.toml app configuration file generated for django-inertia-react on 2025-07-31T02:02:23+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'django-inertia-react'
primary_region = 'sin'
# console_command = 'uv run python manage.py shell'

[build]

[deploy]
release_command = 'uv run python manage.py migrate --noinput'

[env]
PORT = '8000'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'off'
auto_start_machines = false
min_machines_running = 1
max_machines_running = 1
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
memory = '512mb'
cpu_kind = "shared"
cpus = 1

[[statics]]
guest_path = '/app/static'
url_prefix = '/static/'
