# Generated by Django 5.2.4 on 2025-07-30 08:37

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=200)),
                ('driver_number', models.CharField(max_length=200)),
                ('operating_center_address', models.CharField(max_length=200)),
                ('vehicle_number', models.CharField(max_length=200)),
                ('trailer_number', models.CharField(max_length=200)),
                ('miles_driven', models.PositiveIntegerField()),
                ('shipper', models.CharField(max_length=200)),
                ('commodity', models.CharField(max_length=200)),
                ('load_number', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), verbose_name='Created at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('time_point', models.PositiveIntegerField()),
                ('remark', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), verbose_name='Created at')),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='logbooks.logbook')),
            ],
        ),
    ]
