# Generated by Django 5.2.4 on 2025-07-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='miles_driven',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
