# Generated by Django 5.2.4 on 2025-07-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0002_alter_logbook_miles_driven'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='driver_initials',
            field=models.CharField(default='SB', max_length=10),
            preserve_default=False,
        ),
    ]
