# Generated by Django 5.2.4 on 2025-07-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0003_logbook_driver_initials'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='codriver_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
