# Generated by Django 5.2.4 on 2025-07-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0004_logbook_codriver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='status',
            field=models.CharField(choices=[('OFF_DUTY', 'OFF_DUTY'), ('SLEEPER_BERTH', 'SLEEPER_BERTH'), ('DRIVING', 'DRIVING'), ('ON_DUTY', 'ON_DUTY'), ('DELIVERED', 'DELIVERED')], max_length=20),
        ),
    ]
